{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mobile.tech.pitel",
    "module": "PitelSdk",
    "version": "v1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "DemoProdReleaseApiElements-published",
      "attributes": {
        "brand": "Demo",
        "buildEnv": "prod",
        "com.android.build.api.attributes.ProductFlavor:brand": "Demo",
        "com.android.build.api.attributes.ProductFlavor:buildEnv": "prod",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.pristine",
          "module": "libjingle",
          "version": {
            "requires": "9127"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "libjingle",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.8.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.8.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.8.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.8.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PitelSdk-v1.0.0.aar",
          "url": "PitelSdk-v1.0.0.aar",
          "size": 19023406,
          "sha512": "13d4202a27a49be114cb6617886d8b9c1e4ad3a9b182157807f861d4e86023a4f0b10971c8f6f0d65830cbb242bf307da1d634f257ed1c311941765785aa532c",
          "sha256": "16c7f9d2cfacd7f543f638a57b0c319fe9f2a62b2f84046d5741dc7a87b701dc",
          "sha1": "6454ac5bd60101e7ea89cce6e8320613302407c5",
          "md5": "f6af22c2a617fbfca54b65735efc024f"
        }
      ]
    },
    {
      "name": "DemoProdReleaseRuntimeElements-published",
      "attributes": {
        "brand": "Demo",
        "buildEnv": "prod",
        "com.android.build.api.attributes.ProductFlavor:brand": "Demo",
        "com.android.build.api.attributes.ProductFlavor:buildEnv": "prod",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "33.7.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging-ktx",
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config-ktx",
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics-ktx",
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.3"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.2.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-workmanager",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-kotlinx-serialization-converter",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "com.github.nkzawa",
          "module": "socket.io-client",
          "version": {
            "requires": "0.4.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "5.0.0-rc01"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "5.0.0-rc01"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0-alpha07"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.2.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "com.blankj",
          "module": "utilcodex",
          "version": {
            "requires": "1.31.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.2.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "com.facebook.shimmer",
          "module": "shimmer",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.11"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "com.github.voismart",
          "module": "crypto",
          "version": {
            "requires": "0.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "io.pristine",
          "module": "libjingle",
          "version": {
            "requires": "9127"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "libjingle",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.8.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.8.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.8.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.8.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-identifier"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "PitelSdk-v1.0.0.aar",
          "url": "PitelSdk-v1.0.0.aar",
          "size": 19023406,
          "sha512": "13d4202a27a49be114cb6617886d8b9c1e4ad3a9b182157807f861d4e86023a4f0b10971c8f6f0d65830cbb242bf307da1d634f257ed1c311941765785aa532c",
          "sha256": "16c7f9d2cfacd7f543f638a57b0c319fe9f2a62b2f84046d5741dc7a87b701dc",
          "sha1": "6454ac5bd60101e7ea89cce6e8320613302407c5",
          "md5": "f6af22c2a617fbfca54b65735efc024f"
        }
      ]
    },
    {
      "name": "DemoProdReleaseSourcesElements-published",
      "attributes": {
        "brand": "Demo",
        "buildEnv": "prod",
        "com.android.build.api.attributes.ProductFlavor:brand": "Demo",
        "com.android.build.api.attributes.ProductFlavor:buildEnv": "prod",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "PitelSdk-v1.0.0-sources.jar",
          "url": "PitelSdk-v1.0.0-sources.jar",
          "size": 1103320,
          "sha512": "2b2fe460c5e1ca54d2934a5c2e6d59dbc4d674b616f2e2983224c0c3f1dd3e759e8432bd993f9ce4bdd03c98de2f5d90255391e00fc5b6096ead45f315a3dee9",
          "sha256": "1f1306a8f9f181d058117d3a8c555aece33ab34a11c43e2a0f9d8f87f698c4a0",
          "sha1": "d41eb9423c29b03fa4dd411d294132027240f3b2",
          "md5": "59af576fedeaebd31f610b744278175e"
        }
      ]
    }
  ]
}
