{
  "formatVersion": "1.1",
  "component": {
    "group": "com.magic.sdk",
    "module": "AdsSdk",
    "version": "v2.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-lite",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-ktx",
          "version": {
            "requires": "19.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "AdsSdk-v2.3.3.aar",
          "url": "AdsSdk-v2.3.3.aar",
          "size": 709679,
          "sha512": "676937304f3842bd4682ef970d3976a438273e25ba371e38eeeeaf930c2c46ad3bdfd719ce41d001c01f4da26e5565cb905b31989997859616f75ca5067ddc53",
          "sha256": "d5b81ffc132a7a8f97f4b9c447f31e88652e9cba3498e607781203909f18fdd3",
          "sha1": "706a6883947e9c8098b7943267642fb3b79cf0d0",
          "md5": "1abd565450a084bf98d43f13ec6f067c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics-ktx",
          "version": {
            "requires": "22.1.2"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ads",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "com.facebook.shimmer",
          "module": "shimmer",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-lite",
          "version": {
            "requires": "23.6.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-ktx",
          "version": {
            "requires": "19.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "AdsSdk-v2.3.3.aar",
          "url": "AdsSdk-v2.3.3.aar",
          "size": 709679,
          "sha512": "676937304f3842bd4682ef970d3976a438273e25ba371e38eeeeaf930c2c46ad3bdfd719ce41d001c01f4da26e5565cb905b31989997859616f75ca5067ddc53",
          "sha256": "d5b81ffc132a7a8f97f4b9c447f31e88652e9cba3498e607781203909f18fdd3",
          "sha1": "706a6883947e9c8098b7943267642fb3b79cf0d0",
          "md5": "1abd565450a084bf98d43f13ec6f067c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "AdsSdk-v2.3.3-sources.jar",
          "url": "AdsSdk-v2.3.3-sources.jar",
          "size": 69317,
          "sha512": "b6e59dff7185bb6c78e10048b9397eda97b5c84d09391c93ea457fd6019c17b461c9bbe41f7ccb6f510b8f12009368fac4b31c2b9c444a67516fcc5776918c09",
          "sha256": "8498662c7c593de64266f5b74822a704a2dba376ce50f0ce2f90a73406aaa31a",
          "sha1": "50276e29c217b778497bbefe41ee8f0ce62f413c",
          "md5": "06b5ef0e43cf7a72d5f34253beb269af"
        }
      ]
    }
  ]
}
