{
  "formatVersion": "1.1",
  "component": {
    "group": "com.magic.sdk",
    "module": "AdsSdk",
    "version": "v1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-ktx"
        },
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-lite",
          "version": {
            "requires": "22.6.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "AdsSdk-v1.1.7.aar",
          "url": "AdsSdk-v1.1.7.aar",
          "size": 746306,
          "sha512": "71f9ea8a35d0025b3f03e5a7e6922578904942efd9eacb6a82f40aaca5be600be9dede44803be0d7702080f01786ea203586c5d9ba69e2d5056285687b1d12c2",
          "sha256": "e5cc1e5857193a2b300982f6dc0ff55571318278c094105771d68195ca0350e8",
          "sha1": "31e65173c35ef0c7a9ef68c91684a01ecb1a7f15",
          "md5": "e329da971282c53e7ab422824766dcda"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "32.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics-ktx"
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ads",
          "version": {
            "requires": "22.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.facebook.shimmer",
          "module": "shimmer",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.blankj",
          "module": "utilcodex",
          "version": {
            "requires": "1.31.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-ktx"
        },
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-lite",
          "version": {
            "requires": "22.6.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "AdsSdk-v1.1.7.aar",
          "url": "AdsSdk-v1.1.7.aar",
          "size": 746306,
          "sha512": "71f9ea8a35d0025b3f03e5a7e6922578904942efd9eacb6a82f40aaca5be600be9dede44803be0d7702080f01786ea203586c5d9ba69e2d5056285687b1d12c2",
          "sha256": "e5cc1e5857193a2b300982f6dc0ff55571318278c094105771d68195ca0350e8",
          "sha1": "31e65173c35ef0c7a9ef68c91684a01ecb1a7f15",
          "md5": "e329da971282c53e7ab422824766dcda"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "AdsSdk-v1.1.7-sources.jar",
          "url": "AdsSdk-v1.1.7-sources.jar",
          "size": 65753,
          "sha512": "8d2dd5e613f3ff326f316f68a1194754085823c57e5febcda35fcf431c0ea4f8623652c4cac97c793bea05a3466b7fe5e872b40c48b31f8bb968b43fd29b7dea",
          "sha256": "532bedefd5095a3548c0a3c33c787cd1ebeff561efa9c7a930f37647955b39b1",
          "sha1": "95b383f7b6071b5e44efcb7373ca3c0fde01c80d",
          "md5": "e254808a18221d089d0f12a9e8986696"
        }
      ]
    }
  ]
}
