{
  "formatVersion": "1.1",
  "component": {
    "group": "com.magic.sdk",
    "module": "AdsSdk",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-lite",
          "version": {
            "requires": "22.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "AdsSdk-v1.0.5.aar",
          "url": "AdsSdk-v1.0.5.aar",
          "size": 669163,
          "sha512": "96cab754e4825197f281576d66c09ccbdbea34eaf071306d61ec9c490ee4980ac352688bf4ab8aaa2e8774c0a790c9a534ea1159bd851979cf08b74190ca41b0",
          "sha256": "fa5ae1c445c92d74ecd0d2bc43d1f775f973e90a44a2f6af9d9cc82d5f62f5f9",
          "sha1": "9aeb795d2e656f2a0c3de3de6d20b291b2c6f74d",
          "md5": "9b4a23fcda24eb06017bab1e2854a731"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "32.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics-ktx"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-ktx"
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "22.2.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ads",
          "version": {
            "requires": "22.2.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-lite",
          "version": {
            "requires": "22.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "AdsSdk-v1.0.5.aar",
          "url": "AdsSdk-v1.0.5.aar",
          "size": 669163,
          "sha512": "96cab754e4825197f281576d66c09ccbdbea34eaf071306d61ec9c490ee4980ac352688bf4ab8aaa2e8774c0a790c9a534ea1159bd851979cf08b74190ca41b0",
          "sha256": "fa5ae1c445c92d74ecd0d2bc43d1f775f973e90a44a2f6af9d9cc82d5f62f5f9",
          "sha1": "9aeb795d2e656f2a0c3de3de6d20b291b2c6f74d",
          "md5": "9b4a23fcda24eb06017bab1e2854a731"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "AdsSdk-v1.0.5-sources.jar",
          "url": "AdsSdk-v1.0.5-sources.jar",
          "size": 44565,
          "sha512": "c1da1ee1dc0576dc039562c704f90d7ca06d63afb81af9cf1839d2554fc6522bf6133021eba040a57551fc7467457b89e59ce3c1ba9aebc674d41d56446fc558",
          "sha256": "c441835ea7f56e90a4546f1d56699aeac711c3c305f4370a1aedab1384db23b0",
          "sha1": "d005d91ce126fb177d03788f9143f3c13c68eab3",
          "md5": "567ae27265ed5bde56d9488ee1445399"
        }
      ]
    }
  ]
}
